use_frameworks!

target 'keyper-ios-sdk_Example' do
  pod 'keyper-ios-sdk', :path => '../'

  target 'keyper-ios-sdk_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
