use_frameworks!

target 'keyper-ios-sdk_Example' do
  pod 'keyper-ios-sdk', :git => 'https://github.com/keyper/keyper-ios-sdk.git', :branch => '0.9.0'

  target 'keyper-ios-sdk_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
